# Generated by Django 3.0.4 on 2020-03-11 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0002_remove_expenseinfo_depense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseinfo',
            name='cost',
            field=models.FloatField(),
        ),
    ]
